// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: login_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const loginUser = `-- name: LoginUser :one
SELECT id FROM passwordLogin WHERE email = $1 AND password = $2 LIMIT 1
`

type LoginUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Email, arg.Password)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
