// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type Eplatform string

const (
	EplatformNeovim  Eplatform = "neovim"
	EplatformWeb     Eplatform = "web"
	EplatformDesktop Eplatform = "desktop"
	EplatformMobile  Eplatform = "mobile"
	EplatformCli     Eplatform = "cli"
	EplatformVscode  Eplatform = "vscode"
)

func (e *Eplatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Eplatform(s)
	case string:
		*e = Eplatform(s)
	default:
		return fmt.Errorf("unsupported scan type for Eplatform: %T", src)
	}
	return nil
}

type NullEplatform struct {
	Eplatform Eplatform `json:"eplatform"`
	Valid     bool      `json:"valid"` // Valid is true if Eplatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEplatform) Scan(value interface{}) error {
	if value == nil {
		ns.Eplatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Eplatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEplatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Eplatform), nil
}

type Oauth struct {
	ID       uuid.UUID      `json:"id"`
	UserID   uuid.NullUUID  `json:"user_id"`
	Provider sql.NullString `json:"provider"`
	Avatar   sql.NullString `json:"avatar"`
	Email    sql.NullString `json:"email"`
	Username sql.NullString `json:"username"`
}

type Passwordlogin struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"user_id"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	LastLogin sql.NullTime   `json:"last_login"`
}

type Session struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.NullUUID  `json:"user_id"`
	AccessToken     sql.NullString `json:"access_token"`
	RefreshToken    sql.NullString `json:"refresh_token"`
	Platform        NullEplatform  `json:"platform"`
	Method          sql.NullString `json:"method"`
	OauthID         uuid.NullUUID  `json:"oauth_id"`
	PasswordLoginID uuid.NullUUID  `json:"password_login_id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	LastLogin       sql.NullTime   `json:"last_login"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	UserName  sql.NullString `json:"user_name"`
	Email     sql.NullString `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
	LastLogin sql.NullTime   `json:"last_login"`
}
