// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sign_up_password.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const signupWithPassword = `-- name: SignupWithPassword :one
insert into PasswordLogin (id , user_id , email , password , last_login)
values ( gen_random_uuid(), $1 , $2 , $3 , NOW() )
returning id
`

type SignupWithPasswordParams struct {
	UserID   uuid.NullUUID  `json:"user_id"`
	Email    string         `json:"email"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) SignupWithPassword(ctx context.Context, arg SignupWithPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, signupWithPassword, arg.UserID, arg.Email, arg.Password)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
