// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_session_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, access_token, refresh_token, platform, created_at, last_login FROM SESSIONS
WHERE id = $1 limit 1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Platform,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}
