// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: logout.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const logoutDeleteSession = `-- name: LogoutDeleteSession :exec
DELETE FROM Sessions WHERE id = $1
`

func (q *Queries) LogoutDeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, logoutDeleteSession, id)
	return err
}
