// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const authenicateUser = `-- name: AuthenicateUser :one
SELECT EXISTS (
  SELECT 1
  FROM sessions 
  WHERE user_id = $1::uuid
  AND access_token = $2::string
)
`

type AuthenicateUserParams struct {
	Userid      uuid.UUID `json:"userid"`
	Accesstoken string    `json:"accesstoken"`
}

func (q *Queries) AuthenicateUser(ctx context.Context, arg AuthenicateUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, authenicateUser, arg.Userid, arg.Accesstoken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
