// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_session.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateAccessToken = `-- name: UpdateAccessToken :one
UPDATE SESSIONS
SET access_token = $2, last_login = NOW()
WHERE id = $1
RETURNING access_token
`

type UpdateAccessTokenParams struct {
	ID          uuid.UUID `json:"id"`
	AccessToken string    `json:"access_token"`
}

func (q *Queries) UpdateAccessToken(ctx context.Context, arg UpdateAccessTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateAccessToken, arg.ID, arg.AccessToken)
	var access_token string
	err := row.Scan(&access_token)
	return access_token, err
}
