// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: workspaces_create.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
insert into workspaces (id, name, owner, updated_at, created_at, description) values (
  gen_random_uuid(),$1, $2, NOW(), NOW(), $3
)
returning id, owner, name, description, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name        string         `json:"name"`
	Owner       uuid.UUID      `json:"owner"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.Owner, arg.Description)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
