name: setup
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.20'
      - name: Echo Go version
        run: go version
