name: setup
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
jobs:
  setup:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21.x']
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          install-mode: "binary"
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
